### ISSUE TITLE
Post on thunderstore without zip

### ISSUE THREAD

**Issue by KlutzyBubbles** [EliteMasterEric/Coroner#3] opened 2023-12-05 11:59 UTC
The mod when downloaded from thunderstore contains a zip file with a duplicate dll. Only affects v1.1.0

While there are no functional issues with this, it throws an error in the console which could confuse people who are installing it.

**Comment by EliteMasterEric** [comment] 2023-12-05 21:50
Thank you for this report, the issue was caused by my build script to create the ZIP. Should be fixed for 1.2.0

**Comment by EliteMasterEric** [comment] 2023-12-17 02:13
Was fixed in 1.3.0

**Closed by EliteMasterEric** 2023-12-17 02:13 UTC
Labels: bug
